FileVersion = 1
Projects = {SPRIV-Cross = {Path = "SPRIV-Cross"}}

[Configs.Test.Win32]
ConfigSelections = {corlib = {Config = "Debug"}}

[Configs.Test.Win64]
ConfigSelections = {corlib = {Config = "Debug"}}
